/** DCL (GRANT, REVOKE)
	: ADMIN 계정으로 실행해야 함
*/

-- hanny 계정 생성 및 권한 부여
CREATE USER hanny IDENTIFIED BY 1234;
GRANT CREATE SESSION TO hanny;
GRANT CREATE USER, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO hanny;
GRANT CREATE PROCEDURE TO hanny;
commit;

-- 테이블 스페이스 할당
ALTER USER hanny DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

